selecao:
  server:
    port: 8082

server.port: ${selecao.server.port}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    # url: jdbc:postgresql://localhost:5433/selecao
    url: jdbc:postgresql://postgres:5432/selecao
    username: postgres
    password: 123456
  main:
    allow-bean-definition-overriding: true
  jackson.deserialization.fail-on-unknown-properties: true
  rabbitmq:
    username: rabbit666
    password: melhorsenhadomundo
    host: rabbitmq
    # host: localhost

fila.entrada: queue-familia-waiting
fila.finalizado: queue-familia-done

eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://ms-discovery:8761/eureka

elasticsearch.index: selecao
elasticsearch.base.address: http://localhost:9200/${elasticsearch.index}
#elasticsearch.base.address: http://elasticsearch:9200/${elasticsearch.index}